### ISSUE TITLE
Error when starting mod with fabric

### ISSUE THREAD

**Issue by inurentto** [Snownee/Jade#115]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Mod version

5.99.2

### Modloader version

Fabric: 0.14.6

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/pyrb6GaC

### Issue description

When making a custom modpack with fabric and starting it the game crashes with the message:

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'jade'!
Exit Code: -1

**Comment by Snownee** [comment]
Do you have a crash report?

**Comment by rekrapnella** [comment]
I have the same issue when trying to load Jade. heres the Crash report

[crash-2022-05-28_14.58.17-client.txt](https://github.com/Snownee/Jade/files/8791682/crash-2022-05-28_14.58.17-client.txt)

**Comment by Snownee** [comment]
should be fixed in the latest version i think?

**Comment by inurentto** [comment]
Yup works in latest version!

**Comment by pavog** [comment]
Nope, it's not fixed for me...

I used [Jade-1.18.2-fabric-5.99.3.jar](https://www.curseforge.com/minecraft/mc-mods/jade/files/3815553) on my fabric 1.18.2 (0.14.6) server and it still show me the exact same error message.


```
Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'jade'!
```


Full log: https://mclo.gs/fscqbPN

**Comment by Snownee** [comment]
@pavog just install fabric api

**Comment by pavog** [comment]
Thanks, it works when I install fabric api.
Maybe you can add a dependency check that prints an error message saying that the user needs to install fabric api?

**Comment by pavog** [comment]
And maybe you can add Fabric API to the dependencies in Curseforge?
I mean like with the "Related Projects" -> "Dependencies" for the Fabric releases.

Like it is here with the incompatible mods.
https://www.curseforge.com/minecraft/mc-mods/jade/files/3815553
